#title in header
title: "blog @ ncastillo.xyz"

#main info
#owner
owner: "Bienvenido al blog de Nícolas Castillo"
email: false
info: "Ideas, apuntes y contenido Zzzzzz..."
#description
desc: ""

#menu
menu:
  Archivo: /archives

#index/main page max show posts (in number)
max_post: 10

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: false

# social profile at the footer/bottom
footer: true
placename: false
placelink: false
github: https://github.com/ncr6
linkedin: false
twitter: https://twitter.com/tecncr
instagram: false
stackoverflow: false

# Misc
nanobar: /js/nanobar.min.js
switch_light: ☀️
switch_dark: 🌚

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: false
